#!/usr/bin/env python3
"""Apply Reflector proposals to GitHub as Issues and/or PRs.

Reads proposals JSON from stdin, creates GitHub Issues (and optionally PRs)
in the agent-skills repository.

Usage:
    echo '{"proposals": [...]}' | python3 apply_proposals.py \
        --repo git@github.com:user/agent-skills.git \
        --auto-reflection false

Requires: gh CLI authenticated with appropriate permissions.
"""

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path


def get_repo_name(repo_url: str) -> str:
    """Extract owner/repo from git URL."""
    # git@github.com:owner/repo.git → owner/repo
    # https://github.com/owner/repo.git → owner/repo
    match = re.search(r"[:/]([^/]+/[^/]+?)(?:\.git)?$", repo_url)
    if match:
        return match.group(1)
    return repo_url


def get_existing_issues(repo: str) -> set[str]:
    """Get titles of existing open issues with 'reflector' label."""
    try:
        result = subprocess.run(
            ["gh", "issue", "list", "--repo", repo, "--label", "reflector",
             "--state", "open", "--json", "title", "--limit", "100"],
            capture_output=True, text=True, check=True,
        )
        issues = json.loads(result.stdout)
        return {issue["title"] for issue in issues}
    except (subprocess.CalledProcessError, json.JSONDecodeError):
        return set()


def get_existing_prs(repo: str) -> set[str]:
    """Get titles of existing open PRs."""
    try:
        result = subprocess.run(
            ["gh", "pr", "list", "--repo", repo,
             "--state", "open", "--json", "title", "--limit", "100"],
            capture_output=True, text=True, check=True,
        )
        prs = json.loads(result.stdout)
        return {pr["title"] for pr in prs}
    except (subprocess.CalledProcessError, json.JSONDecodeError):
        return set()


def create_issue(repo: str, proposal: dict) -> bool:
    """Create a GitHub Issue for a proposal."""
    title = f"[Reflector] {proposal['title']}"
    label = f"reflector,{proposal['type']},{proposal['priority']}"

    body_parts = [
        f"## {proposal['title']}",
        "",
        f"**Type**: `{proposal['type']}` | **Priority**: `{proposal['priority']}`",
        "",
    ]

    if proposal.get("target_skill"):
        body_parts.append(f"**Target skill**: `{proposal['target_skill']}`")
    if proposal.get("namespace"):
        body_parts.append(f"**Namespace**: `{proposal['namespace']}`")

    body_parts.extend([
        "",
        "### Description",
        "",
        proposal.get("description", ""),
        "",
        "### Evidence",
        "",
        proposal.get("evidence", ""),
    ])

    if proposal.get("suggested_content"):
        body_parts.extend([
            "",
            "### Suggested SKILL.md",
            "",
            "```markdown",
            proposal["suggested_content"],
            "```",
        ])

    body_parts.extend([
        "",
        "---",
        "*Generated by skill-reflector*",
    ])

    body = "\n".join(body_parts)

    try:
        # Use a temp file to avoid shell escaping issues
        with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
            f.write(body)
            body_file = f.name

        subprocess.run(
            ["gh", "issue", "create", "--repo", repo,
             "--title", title, "--body-file", body_file, "--label", label],
            check=True, capture_output=True, text=True,
        )
        Path(body_file).unlink(missing_ok=True)
        print(f"  Created issue: {title}", file=sys.stderr)
        return True
    except subprocess.CalledProcessError as e:
        print(f"  Failed to create issue: {title}: {e.stderr}", file=sys.stderr)
        Path(body_file).unlink(missing_ok=True)
        return False


def create_pr(repo: str, proposal: dict, skills_dir: str) -> bool:
    """Create a PR for new_skill or improvement proposals (AUTO_REFLECTION=true)."""
    # For now, just create an issue. PR creation with file changes requires
    # cloning the repo and making changes, which adds complexity.
    # TODO: implement full PR workflow
    print(f"  PR creation not yet implemented, falling back to issue", file=sys.stderr)
    return create_issue(repo, proposal)


def main():
    parser = argparse.ArgumentParser(description="Apply proposals to GitHub")
    parser.add_argument("--repo", required=True, help="agent-skills repo URL")
    parser.add_argument("--auto-reflection", default="false",
                        help="Create PRs in addition to issues")
    args = parser.parse_args()

    repo = get_repo_name(args.repo)
    auto_reflection = args.auto_reflection.lower() == "true"

    # Read proposals from stdin
    raw = sys.stdin.read().strip()
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        # Try to extract JSON from markdown code fences
        match = re.search(r"```(?:json)?\s*\n(.*?)\n```", raw, re.DOTALL)
        if match:
            data = json.loads(match.group(1))
        else:
            print("Error: Could not parse proposals JSON from stdin", file=sys.stderr)
            sys.exit(1)

    proposals = data.get("proposals", [])
    if not proposals:
        summary = data.get("summary", "No proposals generated.")
        print(f"Summary: {summary}", file=sys.stderr)
        print("No proposals to apply.", file=sys.stderr)
        return

    print(f"Summary: {data.get('summary', '')}", file=sys.stderr)
    print(f"Processing {len(proposals)} proposal(s)...", file=sys.stderr)

    # Check for duplicates
    existing_titles = get_existing_issues(repo) | get_existing_prs(repo)

    created = 0
    skipped = 0
    for proposal in proposals:
        title = f"[Reflector] {proposal['title']}"
        if title in existing_titles:
            print(f"  Skipping duplicate: {title}", file=sys.stderr)
            skipped += 1
            continue

        if auto_reflection and proposal["type"] in ("new_skill", "improvement"):
            success = create_pr(repo, proposal, "")
        else:
            success = create_issue(repo, proposal)

        if success:
            created += 1

    print(f"\nDone: {created} created, {skipped} skipped.", file=sys.stderr)


if __name__ == "__main__":
    main()
